name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    - name: List directory for debugging
      run: ls -R ./chef

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image (update directory if Dockerfile is in a subdirectory)
    - name: Build Docker image
      run: docker build ./chef --file ./chef/Dockerfile --tag travelmail26/cheftest:latest

    # Step 4: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push travelmail26/cheftest:latest
