name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Secrets
      run: |
        echo "Checking secrets passed to GitHub Actions:"
        echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}"
        echo "FIREBASE_KEY=${{ secrets.FIREBASE_KEY }}"
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
        echo "PERPLEXITY_KEY=${{ secrets.PERPLEXITY_KEY }}"
        echo "SERVICE_ACCOUNT_FILE=${{ secrets.SERVICE_ACCOUNT_FILE }}"
        echo "SERVICE_ACCOUNT_FILE_PH=${{ secrets.SERVICE_ACCOUNT_FILE_PH }}"
        echo "TELEGRAM_DEV_KEY=${{ secrets.TELEGRAM_DEV_KEY }}"
        echo "TELEGRAM_KEY=${{ secrets.TELEGRAM_KEY }}"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '427.0.0'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: "cheftest-f174c"

    - name: Configure Docker authentication
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t travelmail26/cheftest:latest .
        docker push travelmail26/cheftest:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy chef-bot \
          --image travelmail26/cheftest:latest \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars ENVIRONMENT=${{ secrets.ENVIRONMENT }},\
FIREBASE_KEY=${{ secrets.FIREBASE_KEY }},\
OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},\
PERPLEXITY_KEY=${{ secrets.PERPLEXITY_KEY }},\
SERVICE_ACCOUNT_FILE=${{ secrets.SERVICE_ACCOUNT_FILE }},\
SERVICE_ACCOUNT_FILE_PH=${{ secrets.SERVICE_ACCOUNT_FILE_PH }},\
TELEGRAM_DEV_KEY=${{ secrets.TELEGRAM_DEV_KEY }},\
TELEGRAM_KEY=${{ secrets.TELEGRAM_KEY }}
