name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '427.0.0'
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: "your-google-project-id"

    - name: Configure Docker authentication
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/your-google-project-id/your-service-name:latest .
        docker push gcr.io/your-google-project-id/your-service-name:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy your-service-name \
          --image gcr.io/your-google-project-id/your-service-name:latest \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars ENVIRONMENT=${{ secrets.ENVIRONMENT }},\
FIREBASE_KEY=${{ secrets.FIREBASE_KEY }},\
OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},\
PERPLEXITY_KEY=${{ secrets.PERPLEXITY_KEY }},\
SERVICE_ACCOUNT_FILE=${{ secrets.SERVICE_ACCOUNT_FILE }},\
SERVICE_ACCOUNT_FILE_PH=${{ secrets.SERVICE_ACCOUNT_FILE_PH }},\
TELEGRAM_DEV_KEY=${{ secrets.TELEGRAM_DEV_KEY }},\
TELEGRAM_KEY=${{ secrets.TELEGRAM_KEY }}
